import palm from './images/palmsq.jpg';
import cabo from './images/cabosq.jpg';
import cocktails from './images/cocktailsq.jpg';
import float from './images/floatsq.jpg';
import view from './images/viewsq.jpg';
import reflections from './images/reflectionsq.jpg';
import galley from './images/galleybaysq.jpg';
import barrington from './images/fortsq.jpg';
import waterfront from './images/waterfrontsq.jpg';
import marina from './images/marinasq.jpg';
import mamora from './images/mamorasq.jpg';
import moon from './images/halfmoonsq.jpg';
import stingRay from './images/stingraysq.jpg';
import cove from './images/coverestsq.jpg';
import swing from './images/swingsq.jpg';

const posts = [

 {
  id: 1,
  author: 'Kelly Rowland',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: palm,
 },
 {
  id: 2,
  author: 'Beyonce Knowles',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: cabo,
 },
 {
  id: 3,
  author: 'Sugar Ray',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: cocktails,
 },
 {
  id: 4,
  author: 'Ariana Grande',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: float,
 },
 {
  id: 5,
  author: 'Whitney Houston',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: view,
 },
 {
  id: 6,
  author: 'Stevie Knicks',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: reflections,
 },

 {
  id: 7,
  author: 'Madonna',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur",
  image: galley,
 },
 {
  id: 8,
  author: 'Mariah Carey',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: barrington,
 },
 {
  id: 9,
  author: 'Rihanna',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: waterfront,
 },
 {
  id: 10,
  author: 'Britney Spears',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: swing,
 },
 {
  id: 11,
  author: 'Christina Aguilera',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: marina,
 },
 {
  id: 12,
  author: 'P!nk',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: mamora,
 },
 {
  id: 13,
  author: 'Kurt Cobain',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: moon,
 },
 {
  id: 14,
  author: 'Kanye West',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur.",
  image: stingRay,
 },
 {
  id: 15,
  author: 'Jay-Z',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: cove,
 },

 {
  id: 1,
  author: 'Kelly Rowland',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: palm,
 },
 {
  id: 2,
  author: 'Beyonce Knowles',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: cabo,
 },
 {
  id: 3,
  author: 'Sugar Ray',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: cocktails,
 },
 {
  id: 4,
  author: 'Ariana Grande',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: float,
 },
 {
  id: 5,
  author: 'Whitney Houston',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: view,
 },
 {
  id: 6,
  author: 'Stevie Knicks',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: reflections,
 },

 {
  id: 7,
  author: 'Madonna',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur",
  image: galley,
 },
 {
  id: 8,
  author: 'Mariah Carey',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: barrington,
 },
 {
  id: 9,
  author: 'Rihanna',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: waterfront,
 },
 {
  id: 10,
  author: 'Britney Spears',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: swing,
 },
 {
  id: 11,
  author: 'Christina Aguilera',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: marina,
 },
 {
  id: 12,
  author: 'P!nk',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: mamora,
 },
 {
  id: 13,
  author: 'Kurt Cobain',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: moon,
 },
 {
  id: 14,
  author: 'Kanye West',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur.",
  image: stingRay,
 },
 {
  id: 15,
  author: 'Jay-Z',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: cove,
 },

 {
  id: 1,
  author: 'Kelly Rowland',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: palm,
 },
 {
  id: 2,
  author: 'Beyonce Knowles',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: cabo,
 },
 {
  id: 3,
  author: 'Sugar Ray',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: cocktails,
 },
 {
  id: 4,
  author: 'Ariana Grande',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: float,
 },
 {
  id: 5,
  author: 'Whitney Houston',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: view,
 },
 {
  id: 6,
  author: 'Stevie Knicks',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: reflections,
 },

 {
  id: 7,
  author: 'Madonna',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur",
  image: galley,
 },
 {
  id: 8,
  author: 'Mariah Carey',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: barrington,
 },
 {
  id: 9,
  author: 'Rihanna',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: waterfront,
 },
 {
  id: 10,
  author: 'Britney Spears',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: swing,
 },
 {
  id: 11,
  author: 'Christina Aguilera',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: marina,
 },
 {
  id: 12,
  author: 'P!nk',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: mamora,
 },
 {
  id: 13,
  author: 'Kurt Cobain',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: moon,
 },
 {
  id: 14,
  author: 'Kanye West',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur.",
  image: stingRay,
 },
 {
  id: 15,
  author: 'Jay-Z',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: cove,
 },

 {
  id: 1,
  author: 'Kelly Rowland',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: palm,
 },
 {
  id: 2,
  author: 'Beyonce Knowles',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: cabo,
 },
 {
  id: 3,
  author: 'Sugar Ray',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: cocktails,
 },
 {
  id: 4,
  author: 'Ariana Grande',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: float,
 },
 {
  id: 5,
  author: 'Whitney Houston',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: view,
 },
 {
  id: 6,
  author: 'Stevie Knicks',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: reflections,
 },

 {
  id: 7,
  author: 'Madonna',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur",
  image: galley,
 },
 {
  id: 8,
  author: 'Mariah Carey',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: barrington,
 },
 {
  id: 9,
  author: 'Rihanna',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: waterfront,
 },
 {
  id: 10,
  author: 'Britney Spears',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: swing,
 },
 {
  id: 11,
  author: 'Christina Aguilera',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: marina,
 },
 {
  id: 12,
  author: 'P!nk',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: mamora,
 },
 {
  id: 13,
  author: 'Kurt Cobain',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: moon,
 },
 {
  id: 14,
  author: 'Kanye West',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur.",
  image: stingRay,
 },
 {
  id: 15,
  author: 'Jay-Z',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: cove,
 },

 {
  id: 1,
  author: 'Kelly Rowland',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: palm,
 },
 {
  id: 2,
  author: 'Beyonce Knowles',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: cabo,
 },
 {
  id: 3,
  author: 'Sugar Ray',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: cocktails,
 },
 {
  id: 4,
  author: 'Ariana Grande',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: float,
 },
 {
  id: 5,
  author: 'Whitney Houston',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: view,
 },
 {
  id: 6,
  author: 'Stevie Knicks',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: reflections,
 },

 {
  id: 7,
  author: 'Madonna',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur",
  image: galley,
 },
 {
  id: 8,
  author: 'Mariah Carey',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: barrington,
 },
 {
  id: 9,
  author: 'Rihanna',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: waterfront,
 },
 {
  id: 10,
  author: 'Britney Spears',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: swing,
 },
 {
  id: 11,
  author: 'Christina Aguilera',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: marina,
 },
 {
  id: 12,
  author: 'P!nk',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: mamora,
 },
 {
  id: 13,
  author: 'Kurt Cobain',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: moon,
 },
 {
  id: 14,
  author: 'Kanye West',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur.",
  image: stingRay,
 },
 {
  id: 15,
  author: 'Jay-Z',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: cove,
 },

 {
  id: 1,
  author: 'Kelly Rowland',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: palm,
 },
 {
  id: 2,
  author: 'Beyonce Knowles',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: cabo,
 },
 {
  id: 3,
  author: 'Sugar Ray',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: cocktails,
 },
 {
  id: 4,
  author: 'Ariana Grande',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: float,
 },
 {
  id: 5,
  author: 'Whitney Houston',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: view,
 },
 {
  id: 6,
  author: 'Stevie Knicks',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: reflections,
 },

 {
  id: 7,
  author: 'Madonna',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur",
  image: galley,
 },
 {
  id: 8,
  author: 'Mariah Carey',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: barrington,
 },
 {
  id: 9,
  author: 'Rihanna',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: waterfront,
 },
 {
  id: 10,
  author: 'Britney Spears',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: swing,
 },
 {
  id: 11,
  author: 'Christina Aguilera',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: marina,
 },
 {
  id: 12,
  author: 'P!nk',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: mamora,
 },
 {
  id: 13,
  author: 'Kurt Cobain',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: moon,
 },
 {
  id: 14,
  author: 'Kanye West',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur.",
  image: stingRay,
 },
 {
  id: 15,
  author: 'Jay-Z',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: cove,
 },

 {
  id: 1,
  author: 'Kelly Rowland',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: palm,
 },
 {
  id: 2,
  author: 'Beyonce Knowles',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: cabo,
 },
 {
  id: 3,
  author: 'Sugar Ray',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: cocktails,
 },
 {
  id: 4,
  author: 'Ariana Grande',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: float,
 },
 {
  id: 5,
  author: 'Whitney Houston',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: view,
 },
 {
  id: 6,
  author: 'Stevie Knicks',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: reflections,
 },

 {
  id: 7,
  author: 'Madonna',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur",
  image: galley,
 },
 {
  id: 8,
  author: 'Mariah Carey',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: barrington,
 },
 {
  id: 9,
  author: 'Rihanna',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: waterfront,
 },
 {
  id: 10,
  author: 'Britney Spears',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: swing,
 },
 {
  id: 11,
  author: 'Christina Aguilera',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: marina,
 },
 {
  id: 12,
  author: 'P!nk',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: mamora,
 },
 {
  id: 13,
  author: 'Kurt Cobain',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: moon,
 },
 {
  id: 14,
  author: 'Kanye West',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur.",
  image: stingRay,
 },
 {
  id: 15,
  author: 'Jay-Z',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: cove,
 },

 {
  id: 1,
  author: 'Kelly Rowland',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: palm,
 },
 {
  id: 2,
  author: 'Beyonce Knowles',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: cabo,
 },
 {
  id: 3,
  author: 'Sugar Ray',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: cocktails,
 },
 {
  id: 4,
  author: 'Ariana Grande',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: float,
 },
 {
  id: 5,
  author: 'Whitney Houston',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: view,
 },
 {
  id: 6,
  author: 'Stevie Knicks',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: reflections,
 },

 {
  id: 7,
  author: 'Madonna',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur",
  image: galley,
 },
 {
  id: 8,
  author: 'Mariah Carey',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: barrington,
 },
 {
  id: 9,
  author: 'Rihanna',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: waterfront,
 },
 {
  id: 10,
  author: 'Britney Spears',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: swing,
 },
 {
  id: 11,
  author: 'Christina Aguilera',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: marina,
 },
 {
  id: 12,
  author: 'P!nk',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: mamora,
 },
 {
  id: 13,
  author: 'Kurt Cobain',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: moon,
 },
 {
  id: 14,
  author: 'Kanye West',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur.",
  image: stingRay,
 },
 {
  id: 15,
  author: 'Jay-Z',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: cove,
 },

 {
  id: 1,
  author: 'Kelly Rowland',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: palm,
 },
 {
  id: 2,
  author: 'Beyonce Knowles',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: cabo,
 },
 {
  id: 3,
  author: 'Sugar Ray',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: cocktails,
 },
 {
  id: 4,
  author: 'Ariana Grande',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: float,
 },
 {
  id: 5,
  author: 'Whitney Houston',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: view,
 },
 {
  id: 6,
  author: 'Stevie Knicks',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: reflections,
 },

 {
  id: 7,
  author: 'Madonna',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur",
  image: galley,
 },
 {
  id: 8,
  author: 'Mariah Carey',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: barrington,
 },
 {
  id: 9,
  author: 'Rihanna',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: waterfront,
 },
 {
  id: 10,
  author: 'Britney Spears',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: swing,
 },
 {
  id: 11,
  author: 'Christina Aguilera',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: marina,
 },
 {
  id: 12,
  author: 'P!nk',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: mamora,
 },
 {
  id: 13,
  author: 'Kurt Cobain',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: moon,
 },
 {
  id: 14,
  author: 'Kanye West',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur.",
  image: stingRay,
 },
 {
  id: 15,
  author: 'Jay-Z',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: cove,
 },

 {
  id: 1,
  author: 'Kelly Rowland',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: palm,
 },
 {
  id: 2,
  author: 'Beyonce Knowles',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: cabo,
 },
 {
  id: 3,
  author: 'Sugar Ray',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: cocktails,
 },
 {
  id: 4,
  author: 'Ariana Grande',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: float,
 },
 {
  id: 5,
  author: 'Whitney Houston',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: view,
 },
 {
  id: 6,
  author: 'Stevie Knicks',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: reflections,
 },

 {
  id: 7,
  author: 'Madonna',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur",
  image: galley,
 },
 {
  id: 8,
  author: 'Mariah Carey',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: barrington,
 },
 {
  id: 9,
  author: 'Rihanna',
  title: "Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  excerpt: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  image: waterfront,
 },
 {
  id: 10,
  author: 'Britney Spears',
  title: "Dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  excerpt: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  image: swing,
 },
 {
  id: 11,
  author: 'Christina Aguilera',
  title: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  excerpt: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  image: marina,
 },
 {
  id: 12,
  author: 'P!nk',
  title: "Aliquet lectus proin nibh nisl condimentum id venenatis",
  excerpt: "Nibh ipsum consequat nisl vel pretium. Sed id semper risus in hendrerit gravida. A iaculis at erat pellentesque. Mauris a diam maecenas sed enim ut. Duis tristique sollicitudin nibh sit amet commodo nulla.",
  image: mamora,
 },
 {
  id: 13,
  author: 'Kurt Cobain',
  title: "Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.",
  excerpt: "In pellentesque massa placerat duis. Integer eget aliquet nibh praesent tristique magna. Facilisi nullam vehicula ipsum a arcu cursus. Molestie a iaculis at erat. Ante metus dictum at tempor commodo.",
  image: moon,
 },
 {
  id: 14,
  author: 'Kanye West',
  title: "Ac felis donec et odio pellentesque. Donec enim diam vulputate ut pharetra sit amet aliquam. Maecenas sed enim ut sem.",
  excerpt: "Penatibus et magnis dis parturient montes nascetur ridiculus mus. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Erat velit scelerisque in dictum non consectetur.",
  image: stingRay,
 },
 {
  id: 15,
  author: 'Jay-Z',
  title: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
  excerpt: "Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  image: cove,
 },


];

export default posts;